export const projects: Project[] = [
  {
    name: "WIP Design",
    href: "https://wip-design.com",
    description: "Community for design engineers",
    tag: "community",
  },
  {
    name: "ASAP Engineering",
    href: "https://asap.engineering",
    description: "Community for technical entrepreneurs",
    tag: "community",
  },
  {
    name: "WaveFinder",
    href: "https://wavefinder.io",
    description: "AI first Advertising Platform for FB and TikTok",
    tag: "software",
  },
  {
    name: "Outr",
    href: "https://outr.io",
    description: "Personalized cold outreach with AI",
    tag: "software",
  },
  {
    name: "Router.so",
    href: "https://router.so",
    description: "Open source form backend for developers",
    tag: "open source",
  },
  {
    name: "BuilderKit",
    href: "https://github.com/alpinecodex/builderkit",
    description: "AI writing tool",
    tag: "open source",
  },
  {
    name: "9d8/next-wp",
    href: "https://wp.9d8.dev",
    description: "Next.js WordPress starter",
    tag: "open source",
  },
  {
    name: "brijr/components",
    href: "https://components.bridger.to",
    description: "Next.js / shadcn/ui components for websites",
    tag: "open source",
  },
  {
    name: "brijr/craft",
    href: "https://bridger.to/craft",
    description: "React design system for websites",
    tag: "open source",
  },
  {
    name: "9d8",
    href: "https://9d8.dev",
    description: "Software Design and Development Studio",
    tag: "ventures",
  },
  {
    name: "Alpine Codex",
    href: "https://alpinecodex.com",
    description: "Marketing Software and Applied AI",
    tag: "ventures",
  },
  {
    name: "Studio Mojave",
    href: "https://studiomojave.com",
    description: "Design Studio in St George, Utah",
    tag: "ventures",
  },
  {
    name: "WIP",
    href: "https://wip.ac",
    description: "Web Design and Development Source",
    tag: "ventures",
  },
];
